server:
  port: 8087
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ubadb
    username: ubadb
    password: ubadb
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  audit-service:
    base-url: http://localhost:8086
  teller-config:
    base-url: http://localhost:8083
  compliance:
    aml-threshold: 10000
    ofac-blocked-actors: blocked-user
  audit-outbox:
    flush-ms: 5000
