server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JKV1QxMjM0NTY=
    expiration-seconds: 3600
  downstream:
    user-management-base-url: http://localhost:8082
    esf-base-url: http://localhost:8084

logging:
  level:
    com.fiserv.uba.gateway: INFO
