spring:
  application:
    name: account-service

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/uba_account_db_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Mayur@143
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: AccountHikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false

server:
  port: 8081

eureka:
  client:
    enabled: false

logging:
  level:
    root: INFO
    com.fiserv.uba: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
