spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uba_account_dev
    username: uba_user
    password: uba_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
