server:
  port: 8084
spring:
  application:
    name: esf-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ubadb
    username: ubadb
    password: ubadb
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
